name             's2i4-base'
maintainer       's2i4 Operations'
maintainer_email 'ops@s2i4.us'
license          'All rights reserved'
description      'Installs/Configures s2i4-base'
long_description 'Installs/Configures s2i4-base'
version          '0.2.2'

depends          'sudo'
depends          'curl'
depends          'ntp'
depends          'htop'
depends          'fail2ban'
depends          'openssh'
depends          'firewall'
depends          'ufw'
depends          'screen'
