name             's2i4-vpcnat'
maintainer       's2i4'
maintainer_email 'ops@s2i4.us'
license          'All rights reserved'
description      'Installs/Configures s2i4-vpcnat'
long_description 'Installs/Configures s2i4-vpcnat'
version          '0.3.5'
depends          'aws-vpc-nat-instance'
depends          'aws-sdk'
